services:
  brixels:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64  # Default for Apple Silicon
    ports:
      - "8502:8501"
    volumes:
      - ./:/app
      - ../data:/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
