name: brixels
channels:
  - conda-forge
dependencies:
  - python=3.14
  - numpy
  - pillow
  - geopandas
  - folium
  - rasterio
  - streamlit
  - ipykernel
  - pip
  # Add some dependencies that work better with Apple Silicon
  - libgdal
  - proj
  - geos
  - pip:
    - opencv-python-headless
    - opencv-contrib-python-headless
    - streamlit-extras
    - streamlit-folium

