[theme]
base="light"
primaryColor="#FF9A72"
backgroundColor="#e8e8e8"
secondaryBackgroundColor="#d0d0d0"
textColor="#333333"
font = "monospace"

[client]
showSidebarNavigation = false
toolbarMode = "auto"

[server]
enableXsrfProtection=false
enableStaticServing = true

[browser]
serverAddress="localhost"